title: "Dyvers Hands Productions"
project: "Dyvers Hands Productions"
description: "Website for Dyver Hands Productions"
author: Dyver Hands Productions LLC
email: team@dyvershands.com
twitter_username: DyversHands
github_username:  DyversHands
#theme: jekyll-theme-primer
#remote_theme: "mmistakes/jekyll-theme-basically-basic"
#remote_theme: dieghernan/chulapa
remote_theme: hydecorp/hydejack@v9.1.6

plugins:
  - jekyll-include-cache
  
